### ISSUE TITLE
revert semi-transparent frame difference preview, or add button to turn it specifically off 

### ISSUE THREAD

**Issue by Cre77** [piskelapp/piskel#1030]
your program's amazing, you're doing god's work and this is legitimately the thing that carried me through my ~2 years experience of spriting.
but pleaaaase either revert or add an option to turn off the semi-transparent "ghosts" of the previous and the next frame. i'm using frames as a crutch for easy directional sprites, and now it's just too jarring to sprite like that, it throws me off :( it's a great idea for animation spriting, but even then, inability to turn off this "ghost" impacts polishing frames, too. there's not even a changelog for this (15.1, i believe).

**Comment by grosbouddha** [comment]
Are you talking about the onion skin feature?
It can be disabled in the right column (see video below)

https://user-images.githubusercontent.com/46651/143136044-32899903-9d25-4c08-9fff-20a99bcf46b7.mp4

**Comment by grosbouddha** [comment]
Are you talking about the onion skin feature?
It can be disabled in the right column (see video below)

https://user-images.githubusercontent.com/46651/143136044-32899903-9d25-4c08-9fff-20a99bcf46b7.mp4

**Comment by Cre77** [comment]
> Are you talking about the onion skin feature? It can be disabled in the right column (see video below)
> 
>  Piskel.-.-.23.November.2021.mp4
that's precisely it. i've no idea how i could have hit the hotkey, since i never even noticed the button x-x
thanks a lot for this, that definitely was a pointless freakout
