### ISSUE TITLE
piskel application not opening on manjaro XFCE and bucket issues with the browser version

### ISSUE THREAD

**Issue by Tryware** [piskelapp/piskel#1048]
Bug description: Piskel binary is not opening in manjaro xfce, it also doesn't shows in the AUR (but somehow it shows in my friend's Manjaro KDE and it opens in his kde plasma). Also in the browser version the bucket doesn't cover all pixels

>Attempted downloading from piskel website
>clicks the file but it still doesn't opens
>Try using the browser version
>Whenever I use the bucket to color something, some pixels stays blank

OS : px@px-pc 
                               -------- 
                               OS: Manjaro Linux x86_64 
                               Host: 81FN Lenovo ideapad 330-15IGM 
                               Kernel: 5.15.16-1-MANJARO 
                               Uptime: 2 hours, 8 mins 
                               Packages: 1178 (pacman) 
                               Shell: bash 5.1.16 
                               Resolution: 1366x768 
                               DE: Xfce 4.16 
                               WM: Xfwm4 
                               WM Theme: Matcha-sea 
                               Theme: Matcha-sea [GTK2], Adwaita [GTK3] 
                               Icons: Papirus-Maia [GTK2], Adwaita [GTK3] 
                               Terminal: xfce4-terminal 
                               Terminal Font: Monospace 12 
                               CPU: Intel Celeron N4000 (2) @ 2.600GHz
                               GPU: Intel GeminiLake [UHD Graphics 600]

![unknown](https://user-images.githubusercontent.com/82564850/151803966-1b9b430e-cfe9-4592-b06a-c33cdcc76bf7.png)

**Comment by ayushmxn** [comment]
According to the [README](https://github.com/piskelapp/piskel#browser-support), Piskel only supports Chrome, Firefox and Edge. Given that it isn't being maintained actively, it sometimes bugs out even in those browsers. I think the best option/workaround is to use the desktop app since it ships with Chromium itself. (#1049).
