### ISSUE TITLE
Exporting with CTRL S in offline version always saves as .piskel

### ISSUE THREAD

**Issue by MrEVandG** [piskelapp/piskel#1059]
This bug(or unless intended) is in the offline version of Pislel App, and it's where you import from an image file, I like using PNGs, and when pressing CTRL+S to save it, it will save as a .piskel file extension. I'd like to ask if there is a way to change the default file format, or this has to be implemented.

**Comment by ayushmxn** [comment]
I believe this is the intended behaviour. Saving as a `.piskel` file allows the application to edit it once it is imported again. You can export as PNG but Piskel won't be able to edit it since it's underlying format is different.

**Comment by MrEVandG** [comment]
Oh. Good to know. Thank you for replying.
