### ISSUE TITLE
Undo & Redo button?

### ISSUE THREAD

**Issue by Breakout-X** [piskelapp/piskel#1125]
I have a small suggestion.
So the Piskel editor is great as it is, don’t get me wrong.
There’s just one small problem: no undo or redo button.
If it is possible, could that be included in the future update?

**Comment by ELedlow** [comment]
There is already an undo and redo function.
To undo use CTRL-Z or CMD-Z.
To redo use CTRL-Y or CMD-SHIFT-Z.

**Comment by Breakout-X** [comment]
Nvm. I found the commands. Apparently it just uses CTRL-Z and CTRL-Y. Sorry about the mixup
