### ISSUE TITLE
Allow adjustment of individual frame timing

### ISSUE THREAD

**Issue by burritojay** [piskelapp/piskel#244]
One easy way to improve the look of simple animations is to adjust the timing of the individual frames, allowing for holds, snappy action, etc. without the need for creating more frames. 

An example: http://forums.wesnoth.org/viewtopic.php?f=23&t=31277&p=551433#p545935

**Comment by juliandescottes** [comment]
Closing as duplicate of #670 (newer issue, but with some code attached + description)
