### ISSUE TITLE
Feature : add "New Piskel" feature in desktop application

### ISSUE THREAD

**Issue by juliandescottes** [piskelapp/piskel#271]
cf #270 

> Regarding the 'new pisklel' button, I just didn't think a lot about this. 
> It's easy to integrate in the webapp because I can just open a new tab with a blank sprite. 
> 
> In the desktop version I guess I could just display a warning if there are unsaved changes, and replace the current sprite with a blank one.

**Comment by applesarefum** [comment]
You could have a tab system in the desktop app where all of your piskels stay open until you close their tab. It may be tedious to put in, though.

**Comment by kult74** [comment]
UP this issue/Feature.

Having a warning for unsaved changes might do the job. That's the common way for many software. Tabs can also be useful but maybe a bit complex to setup.

**Comment by juliandescottes** [comment]
@kult74 There is a warning in the web version, I need to check why this doesn't work in the desktop version.

**Comment by juliandescottes** [comment]
From #270 

> Hi, I am not sure but if you open a link on nodewebkit with target _blank I think it will open a new nodewebkit window.

**Comment by juliandescottes** [comment]
Now implemented for the desktop application

![new_piskel_button](https://cloud.githubusercontent.com/assets/1141550/26746761/df1ab592-47f1-11e7-8b6b-9f2b9669a866.gif)
