### ISSUE TITLE
A tool to draw a outline(border)

### ISSUE THREAD

**Issue by AlexHolly** [piskelapp/piskel#288]
A tool to draw quick outlines around a shape with one click.

**Comment by juliandescottes** [comment]
How would that work.

- select a color
- click on a shape (*)
- one pixel of the chosen color is added to the outline of the shape

* : A shape being an area of connected non-transparent pixels ?

**Comment by AlexHolly** [comment]
I think you described it right.
I don't know if it is possible to implement this tool but here is an example to get the idea.

![example](https://cloud.githubusercontent.com/assets/4741886/8777140/6c087da2-2ef6-11e5-8672-07e35957ec65.png)

The green pixel is the position you click with the tool
Example 1 and 2 looks automaticly where it can go around
Example 3 and 4 is using the "secondary color" to find the right path around the shape.

Another idea woul'd be to use the selection tool  and then use the tool to draw around the selection.
The problem i see is by the pixels that are not connected directly but diagonal.
Is there a way to make multible selections(hold controle)?
