### ISSUE TITLE
Remember last save directory

### ISSUE THREAD

**Issue by AlexHolly** [piskelapp/piskel#291]
Desktop version
Export -> save is always "local/piskel/downloads"

**Comment by juliandescottes** [comment]
I can't reproduce the issue with version 0.5.4 on Windows. 
Which version/OS are you using ?

**Comment by AlexHolly** [comment]
I used 0.5.2. and tried 0.5.4 still the same.
Windows7 64-bit

Is there a way to export the selected layer as png?

**Comment by juliandescottes** [comment]
I thought you mean the "Save" option and not the "Download PNG" / "Download ZIP". I will see if I can improve this.

> Is there a way to export the selected layer as png?

Not really. You can delete layers and undo ... but there's no clean way to do it.
