### ISSUE TITLE
Public URL as sprite no animation

### ISSUE THREAD

**Issue by AlexHolly** [piskelapp/piskel#328]
"Export -> Get public URL"  Is always playing the animation. I need all sprites separated in one line without any animation.
Something like "Export -> Get public URL as stripe".

**Comment by juliandescottes** [comment]
Please add a description :)

**Comment by juliandescottes** [comment]
If you are using Piskel via piskelapp.com and if you have an account, there is an undocumented feature that points to the latest version of your spritesheet : 
http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgIDwvLSrCgw/sprite

This way if your game/game engine accepts URLs for sprites, it should make your life easier.

Is this what you had in mind ?

**Comment by AlexHolly** [comment]
Yes that is the view I was looking for.
Would it be too much to support this view for non registered user's?

**Comment by juliandescottes** [comment]
Hosting and serving images actually starts to be an issue for me. Basically it generates a steady traffic, and it's costing money.

Now for non registered users, there's also the problem of having a constant URL to serve the image. Best we could do would be to generate a hash when the user starts a session and keep it until user refreshes the page.

In your use case, why is a URL better than downloading the PNG ? How do you use the URL afterwards ?

**Comment by AlexHolly** [comment]
Yeah I thought so traffic costs money... I was also asking myself how long the links are valid.

A friend was sharing his sprites to get a quick feedback so they don't have to be valid for a long period of time.

I don't think that Piskel is a Image hoster so I don't expect the links to be valid for ever.
