### ISSUE TITLE
Color Palette : support alpha/transparency

### ISSUE THREAD

**Issue by grosbouddha** [piskelapp/piskel#33]
For now, we don't support partial opacity for colors. We either show 100% opacity colored or totally transparent pixels.

Do we want to support opacity pixels in the future? 

May lead to a bunch of problems/new challenges:
- GIF format does not support semi transparency, we may need to move to/dual-support animated png
- How do you manage overlapping layers of semi-transparent colors? mixed, overlay, discard the first one ?
- how do you manage a future canvas color picker?
- increased complexity (one addtional param to manage a fill color)

Evident benefits are:
- more POWA!
- antialiasing

For now, I'm good not supporting that but I'm curious of your point of view, pros and cons on this one.

**Comment by Forkk** [comment]
Why is this closed? Seems like a pretty important feature.

**Comment by juliandescottes** [comment]
It's closed as duplicate of #210 , forgot to reference it here

However no progress has been made on the other ticket either, except I prototyped it and it was too slow to be usable.

**Comment by chembot141** [comment]
There is a solution to the no transparency problem. Where it says rgb(0,0,0) put instead rgba(0,0,0,0). The last number is transparency. Ex: rgba(0, 255, 0, 0.5) would be green that is 50% transparent.
