### ISSUE TITLE
Show zoom level as text

### ISSUE THREAD

**Issue by hlandau** [piskelapp/piskel#627]
It would be nice if the current zoom level was shown textually somewhere. Right now there's no way to tell when the main viewport is at e.g. 2x.

**Comment by juliandescottes** [comment]
Good point! I could see this located either:
- near the preview/minimap (but it might hide the preview a bit) 
- near the cursor coordinates (bottom right), even though this area is already a bit cluttered when doing a selection

Any other idea?

**Comment by hlandau** [comment]
I think the "status bar" where the cursor coordinates are shown would be best.
