### ISSUE TITLE
Allow pasting images from system clipboard

### ISSUE THREAD

**Issue by VictorCarbajal1** [piskelapp/piskel#645]
It would be great if we could paste images from other programs.

**Comment by juliandescottes** [comment]
I was initially reluctant to add the support for copy paste of image content, because only Chrome seemed to implement it properly. But it looks like Firefox 52 recently added support for this too, so why not!

**Comment by VictorCarbajal1** [comment]
Great! I love your app and I spend a loooot of time creating my sprites
only for mi personal pleasure! Thanks for answer me!!

2017-03-29 19:31 GMT-03:00 Julian Descottes <notifications@github.com>:

**Comment by juliandescottes** [comment]
The clipboard APIs are still a bit messy. This spec looks like the most up-to-date one: https://w3c.github.io/clipboard-apis/#override-copy

Adding a support for the paste event will conflict with the existing "selection_paste" keyboard shortcut. To avoid inconsistencies, the best here will be to forbid editing the shortcuts for cut/copy/paste and directly rely on the associated events.

**Comment by Ehsan199069** [comment]
i loved this . very verycool app thank u so much

**Comment by juliandescottes** [comment]
Thanks :)
Which reminds me that this is fixed, I should close the issue!
