### ISSUE TITLE
Feature Request - Moving around frame

### ISSUE THREAD

**Issue by Cruors** [piskelapp/piskel#658]
Was wondering was there a way to move the cam around the frame beside moving it in the top right because it is hard to get the right position while I'm working on 1080p-4k pixels, I did try and look it up but unless I'm missing it I don't see it.

**Comment by epicabsol** [comment]
Did you try holding the middle mouse button and dragging?

**Comment by Cruors** [comment]
that will do thanks :) let's hope it will help seen as I just had a random problem with Piskel and lost 5 hours of work anyway :)

**Comment by Cruors** [comment]
oh and another thing the selection tool isn't as big as the selected pixel on the left, is that for a reason or just a missing/overlooked feature?

**Comment by juliandescottes** [comment]
> oh and another thing the selection tool isn't as big as the selected pixel on the left, is that for a reason or just a non-existent/overlooked feature?

Do you mean the "pen size" ? I don't really think it's useful for selecting, but if you can explain how it would help you I could reconsider.

> that will do thanks :) let's hope it will help seen as I just had a random problem with Piskel and lost 5 hours of work anyway :)

Sorry about that! But if I understand 1080p-4k correctly, and it means you are actually trying to create sprites that big with Piskel, I'm afraid you will face similar issues frequently :(

**Comment by Cruors** [comment]
The first time it ever had a problem for me really :) and I would use the bigger size to measure so I can get the same size line or spaces without need to keep swapping to pen to see seen as I made my sprite bigger and trimming the fat off it so to say :p

**Comment by juliandescottes** [comment]
Maybe we could have an additional keyboard shortcut in order to mode the viewport.

SHIFT+UP/RIGHT/DOWN/LEFT could move the viewport in the appropriate direction?

**Comment by juliandescottes** [comment]
Now supporting shift+UP/RIGHT/DOWN/LEFT to move the viewport.
