### ISSUE TITLE
Feature Request: JSON Export (similar to C file export)

### ISSUE THREAD

**Issue by rajsite** [piskelapp/piskel#681]
A JSON export very similar to the C file export would be great! I'm looking at vectorizing the output and having JSON data for the points would be a lot easier to manipulate.

Since the numbers are 32bit ints they can pretty safely be stored directly as JSON Numbers instead of as the hex representation (at the very least it's safe in JS). Probably save a few bytes for the general case representing 0x00000000 as 0.

Having metadata in the JSON object and a single long array would be great for the language I'm using.
ie.
```javascript
{
  "name": "test",
  "frame_count": 6,
  "rows": 10,
  "colums": 10,
  "data": [/*...600 numbers...*/]
}
```

If there was a reason for breaking up by frames in the C file (ergonomics?) I would like to suggest creating an array of frame objects instead of a 2d array.

ie.
```javascript
{
  /* Same metadata as above */
  "all_frames": [
    {
      "data": [/*...100 numbers*/]
    }
    /* 5 more frames */
  ]
}
```

Altruistic reason: Keeps the possibility of adding per frame metadata with minimal changes
Selfish reason: The JSON library in the language I'm using takes a huge perf hit with 2D arrays / arrays of arrays and works much better with arrays of scalars or arrays of objects of arrays, etc.

**Comment by juliandescottes** [comment]
Something I previously suggested for very specific export formats is to create a bookmarklet that creates the expected output. 

Even though I added a button for exporting as a C file, I actually regret this since I think it is way too specific to appeal to a broad audience. 

You can see an example of such a bookmarklet at https://gist.github.com/juliandescottes/67627f1e2ea093cd9fd25deebd7a6135

**Comment by filipemeneses** [comment]
I thought it was a good idea to make a more "raw" export and the JSON format would allow other web apps to integrate with this tool.

And thanks for the bookmarklet!

**Comment by filipemeneses** [comment]
I've created a bookmarklet to export to https://github.com/stagas/pixel-art pattern. This might be useful.

https://gist.github.com/filipemeneses/4095dacb052486f99a256c86b63d5597

**Comment by rajsite** [comment]
self-closing stale issue, sounds like there is a bookmarklet workaround 👍
