### ISSUE TITLE
[Feature request] Bigger favicon

### ISSUE THREAD

**Issue by RafaelOliveira** [piskelapp/piskel#694]
With Chrome is possible to create a app with web pages, using the option to add it to the desktop. The page shows without toolbars, like a native app. It creates a shortcut in the desktop, and in the Apps section in Chrome.
But the icon used in Piskel is very small, so it appear very blurry in the shortcut.

(desktop icon / Apps section in Chrome)
![piskel_icon_screenshot](https://cloud.githubusercontent.com/assets/69374/26332739/321fc1b8-3f2f-11e7-99d4-50d127af41d0.png)

I can create a icon for me, but I think would be good to have it in the page, the experience for everyone will be better. I don't know the exact size, maybe 128x128 is enough.

**Comment by juliandescottes** [comment]
Thanks for filing! Which page are you setting as the app? Is it http://www.piskelapp.com?
If so, the fix will probably be to set a better favicon on https://github.com/piskelapp/piskel-website/blob/master/templates/base.html

I have the logo saved as a sprite on my Piskel account so it should be esy to generate whatever resolution we need from http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByDgsSBlBpc2tlbBjZmwkM/edit

**Comment by RafaelOliveira** [comment]
Actually I'm setting the page editor directly. But I'm seeing that the icon is the same as the main page (http://www.piskelapp.com/static/resources/favicon.png), so I will do a pr to change this icon.

I researched some websites that shows the icon with good quality in the Apps section, some of them use 256x256:
https://s4w.cdn.skype.com/0-238-0/images/favicon.ico (skype online)
https://www.irccloud.com/favicon.ico (irccloud)
If it's OK will use this size.

**Comment by juliandescottes** [comment]
Sounds good! 
Would love to see a PR for this (it will have to be on https://github.com/piskelapp/piskel-website)

**Comment by RafaelOliveira** [comment]
The pr was sent.
