### ISSUE TITLE
White color instead of transparent BG on GIF with only 4 colors

### ISSUE THREAD

**Issue by jackyfox** [piskelapp/piskel#700]
Hello! I've tried web and offline PiskelApp to save my small GIF animation. On both I got white color instead of transparent background. I found few threads about over 256 colors issue, but my image have only 4. Please help

Here is my animation [http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgIDfu-quCAw/view](http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgIDfu-quCAw/view)

![gif twitch dwit cheer emote 5](https://cloud.githubusercontent.com/assets/693161/26602829/6c415f14-458d-11e7-9057-390f5bb5d1ec.gif)

**Comment by juliandescottes** [comment]
Transparency also gets deactivated when a layer has transparency (https://github.com/piskelapp/piskel/blob/master/src/js/controller/settings/exportimage/GifExportController.js#L85-L86). In your animation, layer 2 has 0.9 alpha.

Several reasons for this:
- we can't render the alpha channel in a GIF
- we can't rely on the individual layer color count, if a layer is transparent

For the first issue we could probably ignore pixels with less than 0.5 alpha and make pixels with 0.5 alpha or more totally opaque. 

For the second issue I think there is no other choice than counting the colors of the final render. It might be time consuming but we should be able to do it in a worker easily.

**Comment by jackyfox** [comment]
Thanks for answer. 

I just turn alpha of second layer to 1 (now all layers have alpha 1.0), but problem still here.

**Comment by juliandescottes** [comment]
If you like bad workarounds, I have 2 here:
1. (obviously) set the opacity of layer 2 to 1alpha 
2. ideally you should be able to merge & fuse layers. You can almost do the same by doing 
    1. export to PNG spritesheet
    2. import the PNG as a spritesheet
    3. you get this -> http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgMCwrozyCww/edit

**Comment by juliandescottes** [comment]
> 

From your sprite, I just exported and got
![image](http://piskel-imgstore-b.appspot.com/img/5399622b-4579-11e7-bfa6-b331d683c423.gif)

which has a transparent background. (github's own background is white, but I guarantee the background is transparent)

**Comment by juliandescottes** [comment]
or bigger: http://piskel-imgstore-b.appspot.com/img/f53c5133-4579-11e7-a6dc-b331d683c423.gif

**Comment by jackyfox** [comment]
Thank you @juliandescottes I'll use this technic for my future animations =)

**Comment by juliandescottes** [comment]
I am closing the issue now, we will need to open an issue to have a merge that takes the alpha into consideration.

**Comment by Thorbecken** [comment]
For those wondering, having a layer with transparency of 0 also counts as having a alpha layer and will turn the background white.
