### ISSUE TITLE
Unable to access editor

### ISSUE THREAD

**Issue by MetaHazard** [piskelapp/piskel#701]
Any time I attempt to edit any of my sprites, or even create a new sprite I am confronted with an Error screen.  I've tried signing in and out, different browsers and restarting my computer. 

![screenshot 85](https://cloud.githubusercontent.com/assets/29075868/26606742/20f275a6-4561-11e7-909b-0a526fe4887f.png)

**Comment by juliandescottes** [comment]
@MetaHazard can you share your username or some of the pages you are trying to access?

**Comment by juliandescottes** [comment]
Never mind I must have deployed a bad version. rolling back right now

**Comment by juliandescottes** [comment]
Ok, that should be fixed

**Comment by juliandescottes** [comment]
Thanks for reporting the issue so quickly @MetaHazard !

**Comment by MetaHazard** [comment]
Thanks for fixing it so quickly! This whole website is pretty awesome.
