### ISSUE TITLE
there is no undo button and i just lost over an hour of work/ a big project

### ISSUE THREAD

**Issue by drabtomato** [piskelapp/piskel#710]
I cannot get my work back after I accidentally used the paint all pixels tool witch is right beside the paint bucket tool

**Comment by juliandescottes** [comment]
CTRL + Z or CMD + Z is the shortcut to undo

**Comment by drabtomato** [comment]
Oh. Thanks

**Comment by RazorTheSavage** [comment]
redo doesn't work for me
