### ISSUE TITLE
export all frames in different png images Feature

### ISSUE THREAD

**Issue by EPKGames** [piskelapp/piskel#724]
Feature, Export all frames in different png images.
Explanation:
frame 1 on animation_001.png
frame 2 on animation_002.png
frame 3 on animation_003.png
etc.

**Comment by juliandescottes** [comment]
Try the ZIP export:

![image](https://user-images.githubusercontent.com/1141550/28751200-d039cc9c-7501-11e7-910e-d25916238e41.png)

**Comment by EPKGames** [comment]
oooooooooooooooooooooooooooooooo tnx man
tnx

**Comment by juliandescottes** [comment]
np :)
