### ISSUE TITLE
Mozilla always crash after clicking to "Create Sprite"

### ISSUE THREAD

**Issue by StrangeArtist** [piskelapp/piskel#734]
Bug description

### Steps to reproduce the bug
1. go to piskelapp.com
2. Click on Create Sprite

### Environment details
* operating system: Linux Mint
* browser : Mozilla Firefox

2 days ago, I tried Piskelapp.org for the first time, all was working, without loading gifs from other users. Today I can't even create a Sprite. I tried it 4 times, but Mozilla crashed.

**Comment by vermiceli** [comment]
Hi @StrangeArtist, could you try following the documentation [from Mozilla](https://support.mozilla.org/en-US/kb/firefox-crashes-troubleshoot-prevent-and-get-help?redirectlocale=en-US&redirectslug=Firefox+crashes) on what to do when you have a crash?  It has advice on getting the crash logs as well as some preliminary checks like making sure it's not a plugin, or a outdated version.

**Comment by juliandescottes** [comment]
@StrangeArtist I haven't had any specific issue with Firefox. Do you know which version of Firefox you are using? Can you try with a clean profile https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by juliandescottes** [comment]
No feedback, please reopen if this still occurs.
