### ISSUE TITLE
problems with piskel, please help?

### ISSUE THREAD

**Issue by belstar121** [piskelapp/piskel#735]
![page1](https://user-images.githubusercontent.com/31361158/29737772-d1fb983e-8a0b-11e7-8537-b39369855954.jpg)

![page2](https://user-images.githubusercontent.com/31361158/29737783-07869c60-8a0c-11e7-814d-ecf84dcdaa2f.jpg)

Hi

2 issues with piskel driving me mad

1)offline mode has suddenly stopped responding when started, now starts and no buttons working at all 
2)when in online mode , try import my .piskel saves and cannot select option, will not load anything.
currently have no way to access my images?

**Comment by belstar121** [comment]
ok I have changed my browser to Firefox which has allowed my to upload.
its just the offline program?

**Comment by juliandescottes** [comment]
@belstar121 there is bug in v0.12.0 which is related to palettes. I uploaded a fix for OSX but not for windows yet. I can do it later this weekend.

Regarding your screenshot with the import window, which browser are you using?

**Comment by belstar121** [comment]
that was with ie, but its working fine on firefox.

**Comment by juliandescottes** [comment]
Just uploaded v0.12.1 for windows which should fix your issue with the offline version.
