### ISSUE TITLE
Mirror pen w/ 2 or 4 pixel pen

### ISSUE THREAD

**Issue by 63239** [piskelapp/piskel#750]
Bug description
The mirror is offset by one pixel (in the direction of the mirror line) when using the 2x2 or 4x4 pixel brush. (will include an image showing expected result and actual result) the bug only applies to the 2x2 and 4x4 brush the 1x1 and 3x3 brush work as expected. Additionally if the canvas is odd or even in size which changes if the mirror line is a full pixel or in between the bug still applies. It effects both the horizontal and vertical mirror axis.

### Steps to reproduce the bug
1. Open v0.12.1 offline version of piskel
2. Change pen size to 2 or 4
3. Turn on mirror pen
4. Click on the mirror line (or the adjacent tile if canvas is even in size)

### Environment details
* operating system: Windows 10, Offline application version 0.12.1 (was also present in v0.6 I missed a lot of version updates)
* browser (or offline application version):

### Sprite details
The bug applies to all frames and it doesn't matter if the size is odd or even.

Feel free to include a screenshot of the bug, a .piskel file of the sprite or anything else that can help us investigate.

### Image description
The while line marks the mirror line as the canvas in the example is an odd size. The red pixel marks where I clicked with the 2x2 pen. The black pixels show what happens. The blue pixels show what I expect to happen.
![mirror bug](https://user-images.githubusercontent.com/23193908/30888159-f16da3c8-a316-11e7-99d2-424d297f9dc1.PNG)

I assume the reason for this is the with the 2x2 brush it always draws from the bottom right pixel you click on. When using the vertical mirror brush it will mirror your cursor the the same position on the other half of the screen and then draws from the bottom right pixel but this means it ends up drawing towards the mirror line instead of away. offsetting the reflection by 1. This same logic applies to the 4x4 brush as it doesn't have a center point either.

**Comment by juliandescottes** [comment]
Thanks for the detailed report!

**Comment by 63239** [comment]
If there is anything that is unclear about my report I'll be happy to try and explain it better.
