### ISSUE TITLE
GIF repeat settings?

### ISSUE THREAD

**Issue by Leetcore** [piskelapp/piskel#751]
Hey,

can i get repeat value for GIF generation to make a GIF animate just once?

Should be something like repeat -1. Could be a checkbox.

Best regards!

**Comment by juliandescottes** [comment]
Thanks for the feature request! 

This should be feasible by setting the [repeat option](https://github.com/jnordberg/gif.js#options) in the gifjs library we are using. Needs some testing of course :)

I agree with your suggesting, a checkbox would be nice here. Will need to find a wording that is not confusing.
