### ISSUE TITLE
[Feature Request] Addition of Piskel Chrome OS Application to Desktop Applications

### ISSUE THREAD

**Issue by m0nt3-q** [piskelapp/piskel#755]
I have ported Piskel to a Chrome Packaged App, [here](https://drive.google.com/file/d/1DoHB3qSvwur9Pjhjp9Z37v9jAibQOBE_/view?usp=sharing), and would like to know if it can be added into the Wiki?

**Comment by carlsmith** [comment]
I didn't properly test anything, but installed this to see how easy it is, and it just a matter of unzipping the folder and dragging a single file into `chrome://extensions/`, which is pretty cool as an offline option.

Thinking about use cases, this would be handy for people who cannot install stuff normally. For that case, it may be worth making the unzipped CRX file available, as they may not be able to download and unzip stuff either.

**Note**: This uses the offline version of Piskel. For the Chrome Store, it might be better to link to the online version.

**Comment by m0nt3-q** [comment]
Good point. I will change it so that only the CRX file is downloaded.

In regards to using the online version, I hadn't thought about that originally. Sounds like a better idea, I'll implement it along with creating a Github repo for it.

**Comment by juliandescottes** [comment]
Sorry for not seeing this earlier, this is really cool! 

As an extension, the download size is much smaller, and I expect less bugs/inconsistencies than with the current desktop versions using node-webkit. That's also great for ChromeOS users!

Do you plan to write a small doc instructions on how to create the CRX? Then we could make this part of the release, and add a section on https://www.piskelapp.com/download

I would also be happy to give you rights to edit the wiki, that should be doable now that I moved this repository to an organisation. This way you can also add it to https://github.com/piskelapp/piskel/wiki/Desktop-applications

Regarding offline vs online, do you mean standalone vs integrated in piskelapp.com? Right now your extension is using the standalone version (meaning the user can't login in piskelapp and can't save sprite to the gallery). But I think that's fine until we figured out how to 

Small question: the UI looks a bit zoomed out when I use the extension. Is that on purpose (hard to read on non-retina)

**Comment by m0nt3-q** [comment]
I believe that @carlsmith was meaning that version, I'm not entirely sure.

Now that I know it can/will be accepted into the Wiki, I will write a small doc.

I was using the standalone because I have not created an account and didn't think of that an an option for users. I will work on integrating with piskelapp.com.

I had zoomed out for my own preference, and because I wasn't sure if others would ever be using it, I never continued to add a zoom feature. That was planned though.

**Comment by AbsurdGames** [comment]
There is something going wrong in the program... here is an image

![Screenshot 2022-07-11 4 10 13 PM](https://user-images.githubusercontent.com/104153005/178284017-60736f9c-1ea1-46b1-b702-32d4deaed7ab.png)

**Comment by m0nt3-q** [comment]
@AbsurdGames I'm not sure what's happening, and I haven't looked at this code in years. Though you're welcome to fork it [here](https://github.com/m0nt3-q/cros-piskel) and figure out the issue.
