### ISSUE TITLE
[Request] Offline versions for 0.13.0

### ISSUE THREAD

**Issue by vpontin** [piskelapp/piskel#767]
Currently in [download page](https://www.piskelapp.com/download) there offline binaries only for 0.12.1.
Can someone make updated offline builds for windows?

Thanks in advance!

**Comment by juliandescottes** [comment]
Ah I forgot to update the download page, thanks for logging the issue.

In the meantime here are the links for 0.13.0 :
* windows https://drive.google.com/uc?export=download&id=0BwPjxqZA0YlRWTJLR1Z6X0Exa28
* osx https://drive.google.com/uc?export=download&id=0BwPjxqZA0YlRaWFVYW4tdW1vaEk
* linux https://drive.google.com/uc?export=download&id=0BwPjxqZA0YlRTE5PeVpnQzhfUUE

**Comment by juliandescottes** [comment]
(links were updated sometime ago, closing)
