### ISSUE TITLE
Display current frame number

### ISSUE THREAD

**Issue by juliandescottes** [piskelapp/piskel#771]
From twitter.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1141550/34062497-7d4b93bc-e1b2-11e7-9718-379edf63d760.png">

If you have many frames and the frame list doesn't display the current frame, you have no way to know which frame is currently selected. We should display the current frame number somewhere in the UI

**Comment by PrashBricks** [comment]
Yeah, maybe near the size [32 x 32], I would suggest to but it next to the size and make it display like this: 12/15, meaning you have the 12th frame selected and you have 15 frames in total. Good idea!
