### ISSUE TITLE
Piskel art erased after being saved?

### ISSUE THREAD

**Issue by Robopickle2000** [piskelapp/piskel#775]
![broken](https://user-images.githubusercontent.com/35782981/35358611-3823ccae-0125-11e8-8375-296867faf8d5.png)

![broken 2](https://user-images.githubusercontent.com/35782981/35358630-43817eca-0125-11e8-99cf-2675a737116c.png)

![broken 3](https://user-images.githubusercontent.com/35782981/35358635-496c4324-0125-11e8-8bd6-deb6264677de.png)

![broken 4](https://user-images.githubusercontent.com/35782981/35358646-4dc79572-0125-11e8-90c1-d2b073a62b45.png)
)
I've used piskel to make multiple sprites, but when i logged in two of my sprites wouldnt let me edit them (still won't) . only 2 out of the 20 or so i have, it shows the sprite with all my other ones, i click view sprite and its still there, then i click edit sprite and its blank.

(this template is intended for bug reports, erase it when requesting features/enhancements)

### Steps to reproduce the bug
![broken](https://user-images.githubusercontent.com/35782981/35358611-3823ccae-0125-11e8-8375-296867faf8d5.png)

1. go to piskelapp.com
2. select a tool
3. ...

### Environment details
* operating system: Windows 10
* browser (or offline application version): browser

### Sprite details
* number of frames: 1 each
* sprite resolution: 64x64 and 128x128
* session duration: none

Feel free to include a screenshot of the bug, a .piskel file of the sprite or anything else that can help us investigate.

**Comment by Robopickle2000** [comment]
sorry im new to this; im on windows 10 and i was using the browser version

**Comment by juliandescottes** [comment]
Hi! Can you flip your sprites visibility to "public" and add links here? 

Thanks

**Comment by Robopickle2000** [comment]
Hey thanks for replying. Im assuming you only want the two that are missing
to be set to public? Also im not sure how to link them (or i might know how
and just dont know what you need)

try this maybe? https://www.piskelapp.com/user/4759133256417280/public

**Comment by Robopickle2000** [comment]
@juliandescottes 
Im assuming you just want me to make the missing ones public? not all of my sprites?

**Comment by Robopickle2000** [comment]
did you ever figure out if you got the right link because my two sprites
are still missing?

**Comment by juliandescottes** [comment]
@Robopickle2000 I assume you didn't see my edit in my first comment, as I was waiting for an email from you. I'll edit your sprites manually.

**Comment by juliandescottes** [comment]
(and checking your gallery, the sprites you mention in your summary are not public on your page)

**Comment by Robopickle2000** [comment]
@juliandescottes thank you very much, so happy you were able to save them!
