### ISSUE TITLE
[Technical] Duplicate module for grunt tab openning

### ISSUE THREAD

**Issue by GMartigny** [piskelapp/piskel#777]
This is more of an info than an issue, but the module grunt-open is not usefull here.

Since the v0.5.0, grunt-contrib-connect provides [an option to open](https://www.npmjs.com/package/grunt-contrib-connect#open) the served URL into the default browser.
Triming a module and its dependencies can avoid bugs and overheads.

I can provide the PR if this is approuved.

Cheers

**Comment by juliandescottes** [comment]
@GMartigny thanks for the heads up! Feel free to PR if that works :)
