### ISSUE TITLE
Is there any way to save a color pallet? 

### ISSUE THREAD

**Issue by bagelnacho** [piskelapp/piskel#781]
I've yet to find a way to save a color pallet.

**Comment by juliandescottes** [comment]
Yes, either create a new palette from scratch:

![image](https://user-images.githubusercontent.com/1141550/36258009-7489dd42-1259-11e8-80b7-7dc78b2dc66d.png)

Or if you want to clone your "current colors" click on modify while having the "current colors" palette selected.

From the palette edition window you can also import palettes from other software or from images.

**Comment by bagelnacho** [comment]
Wow jesus,that was fast.Thanks.

**Comment by juliandescottes** [comment]
np! closing as it seems to solve your issue.
