### ISSUE TITLE
It says the piskel exe has a detected virus

### ISSUE THREAD

**Issue by NaminBeforeGamin** [piskelapp/piskel#789]
First of all this isn't really a bug. but when I scanned the piskel.exe file on VirusTotal, it said that the file had a detected virus from Cylance.  I'm just making sure this is safe.  Thank you!

**Comment by juliandescottes** [comment]
@NaminBeforeGamin thanks for the info! Which version did you download? The latest from piskelapp.com?

**Comment by juliandescottes** [comment]
Ok it looks like this happens with the last version and is probably related to nwjs. I tried checking the latest nwjs.exe (from https://nwjs.io/downloads/ ) on VirusTotal, and it shows the same warning.

I'm fairly sure this is a false positive, but I will log an issue on the nwjs repository to get some more insights.

**Comment by juliandescottes** [comment]
@NaminBeforeGamin see the answer on the issue I opened. 
I don't plan on requesting nwjs.exe to be whitelisted.
