### ISSUE TITLE
Promoting Piskel to Facebook

### ISSUE THREAD

**Issue by anaufalm** [piskelapp/piskel#795]
Wow, I am looking for an app to create a pixel object and find this [site](https://www.piskelapp.com/), this is a really cool app, I really like it. And that's evident from the many stars in this project.

May I share this preject? So that people know more about this cool project. i will promote it on facebook possible.

**Comment by juliandescottes** [comment]
Hi, thanks for getting in touch. Feel free to share, that's what open source is for I guess :)

**Comment by juliandescottes** [comment]
(closing because it's not really an issue per se, but thanks for the nice words! )

**Comment by anaufalm** [comment]
Hi Julian, I mean I will run Facebook Ads to campaign your project, because
your project is very awesome. I just ask your permission allow me to do
this. :)

**Comment by juliandescottes** [comment]
Ah I misunderstood, sorry. 

I don't encourage you to run ads on Facebook for Piskel, especially if it would cost money to do so, and I can't be responsible for that. I can't prevent you from doing it, but I won't take any responsibility for it. 

I don't use facebook so I might not be aware of the ad system you plan to use. Is there something I can look at/review to see why my permission would be important?

**Comment by anaufalm** [comment]
Ahh dont worry about that, because I contribute to Utopian.io, they give
rewards to every contribution on the open source project. And at this time,
I will promote you project. ;)

Here is one example of the project that I have promoted, and your project
will be promoted like this also clearly and transparently.

https://utopian.io/utopian-io/@naufal/promoting-steepshot-to-indonesian-photographer-11k-people-reach

And, your permission is very needed here. Because the rules are so. If you
allow, I will promote, otherwise I will not. I dont mean to force you, it's
up to you because you're PO here. ;)
