### ISSUE TITLE
"Export selected frame" doesn't resize online

### ISSUE THREAD

**Issue by Ists-Cilveks** [piskelapp/piskel#803]
When choosing to "Export selected frame as PNG file", the scaling doesn't seem to work.
This is happening to me on Chrome, Windows 10, though it's probably happening everywhere.
Kind of a niche thing but still, it should work.

**Comment by juliandescottes** [comment]
Good point, no reason not to resize this export. We might also move it to the PNG tab. I was initially against it but it would make it more discoverable/
