### ISSUE TITLE
Option for using data-uri instead of file name for "Export for PixiJS Movie".

### ISSUE THREAD

**Issue by vilhaum** [piskelapp/piskel#806]
Add an option to put the data-uri in place of the of the file name for the "Export for PixiJS Movie" option. This allows for images to be kept with their JSON animation and to also be packed inline easily using tools like Webpack.

Current:
```json
"meta": {
    "image": "spritesheet.png"
}
```

With option enabled:
```json
"meta": {
    "image": "data:image/png;base64,iVBORw0KGgo..."
}
```

### Steps to reproduce the bug
1. Export for PixiJS Movie.
2. Need additional "replace file name with data-uri" option.

### Environment details
* operating system: Ubuntu 17.10
* offline application version: 0.14.0

**Comment by juliandescottes** [comment]
I can see how this would be useful, would happily accept PRs for this :)
