### ISSUE TITLE
Making bigger canvas?

### ISSUE THREAD

**Issue by imperialblade14** [piskelapp/piskel#808]
Hello!

I was trying to make the canvas bigger than the 32x32 but whenever I go into resize and try to change the amounts in the box it will act like it's typing but stay the same. Tried numerous times to delete the 32 and replace it with something but it just isn't taking it for some reason. Am I doing this wrong or is there another way to make it bigger?

Thank you for your time.

**Comment by juliandescottes** [comment]
Hi @imperialblade14 

This should work fine: type in the inputs and click on resize. 

Can you provide additional information:
- what is your operating system
- which browser are you using / or are you using the desktop application
- can you attach a screenshot of the UI

Thanks

**Comment by juliandescottes** [comment]
Closing for now, feel free to reopen with more details.
