### ISSUE TITLE
Import Spritesheet PNG or JPEG

### ISSUE THREAD

**Issue by MohamedAlFahim** [piskelapp/piskel#825]
It would be very neat if I could simply import an image file with each animation frame in it. Piskel could divide the image into frame images, then treat those frame images as regular Piskel frames.

**Example**
```
xxxxxx
xxxxxx
xxxxxx
```
becomes
```
xx|xx|xx
--------
xx|xx|xx
--------
xx|xx|xx
```

**Comment by MohamedAlFahim** [comment]
A somewhat similar issue already exists

**Comment by juliandescottes** [comment]
Shouldn't that be the import spritesheet feature?

![image](https://user-images.githubusercontent.com/1141550/41190709-32cb7926-6be4-11e8-8d9f-4da36f73d094.png)

UX could be improved though.

**Comment by MohamedAlFahim** [comment]
My mistake. I meant to add having the user drag their mouse to select areas for frames, rather than just a fixed size per frame. @juliandescottes

**Comment by sirdouglasiii** [comment]
I'm currently trying to upload some sprites from a sheet in sequence but i can't seem to get them split in the correct dimesions. Its a sheet of 7 images.
