### ISSUE TITLE
[Feature request] last frame preview

### ISSUE THREAD

**Issue by Nitwel** [piskelapp/piskel#881]
So, first of all, amaizing tool ❤️ , its realy usefull and well designed.

My Idea was that there is an option to enable a preview of the last frame you made. (simular to the preview of the layer beneath)
This would be realy usefull for creating more complex animations and I think is also easy to implement.
The only other thing would be a scroller to change opacity for the last frame.

If this request or feature already exists, Im sorry but I could not find anything about it.

**Comment by blurymind** [comment]
you mean like onion skinning?

**Comment by Nitwel** [comment]
Ah, exactly. Would be really nice to have a button for this because looking it up in the key-shortcuts would be the last place where I look. Or is there one?

**Comment by blurymind** [comment]
we have a button. Its onion icon, on the right

**Comment by Nitwel** [comment]
Ahhhhh, wow, never would have expected that this is the function of the button. Maybe put the option in the settings rather than there because I thought it would have to do something with the preview.

**Comment by blurymind** [comment]
i think its good where it is- makes sense

**Comment by Nitwel** [comment]
Then leave it as it is, personaly I found it confusing but when nobody else has the same problem, it should be fine. But awesome tool you created there, realy enjoying it. ❤️ 👍

**Comment by rkhoury** [comment]
This GitHub issue helped me find this feature! Thanks for asking, and thanks for answering!!
