### ISSUE TITLE
Undo re-toggles the preview for all frames

### ISSUE THREAD

**Issue by xamroot** [piskelapp/piskel#889]
When having more than one frame and having some frames disabled for preview, when undoing any unrelated action all frames which are disabled for preview become active in the preview agian.

### Steps to reproduce the bug
1. go to piskelapp.com
2. add more than one frame
3. toggle all frames for preview except for one (so only one frame is shown in the preview box)
4. begin drawing on the frame which is being shown in the preview
5. press ctrl-z to undo some of your drawing, may take more than one times.
6. you will see that all frames have been re-enabled to show on the preview. you may say that 'well you are undoing the action of disabling the frame' however I have noticed that the order is totally ignored. say you draw a pixel then disable a frame then draw a second and third pixels. undoing twice should just undo the third and second drawn pixels, however I have noticed in this situation the disabled frames would be re-enabled for preview.

### Environment details
* operating system: windows 10
* browser (or offline application version): firefox

### Sprite details
* number of frames: 10
* sprite resolution: 128x128
* session duration: about an hour

It should be simple to replicate assuming it's not a super weird bug, if you guys are not able to replicate I will include screenshots step by step. Thanks all for your time!

**Comment by PoolloverNathan** [comment]
...and it kills the bottom few lines of the sprite right?
common theme: only happens if a frame is hidden
