### ISSUE TITLE
[Feature Request] Exporting .piskel Files from Site to Offline

### ISSUE THREAD

**Issue by JarredC1000** [piskelapp/piskel#890]
So, it may just be that I'm new to the offline editor scene, but it doesn't look like it's possible to properly export GIFs from the site to your computer to edit them there. It would be nice to keep all your layers separate for editing while offline. Also -- not that big of a deal, I think --
 but trying to export your sprite as a GIF and using that GIF in the offline editor results in a little bit of flickering on certain colors.
![Kosarou Commission 2 (2)](https://user-images.githubusercontent.com/52683313/60852903-5053b780-a1bf-11e9-8177-a9db1ba5626c.gif)
Look at the purple visor in the top right corner. Prime example.

**Comment by blurymind** [comment]
gif files contain no layer data - they get flattened when you export as gif.

Are you saying that exporting as piskel flattens them too?

**Comment by JarredC1000** [comment]
Oh, no, no, .piskel files are fine when it comes to exporting, but it seems as if you can't export .piskel files from the website editor, making proper back-and-forth editing from the online to offline editors a hassle.

**Comment by blurymind** [comment]
you mean this editor?
https://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgICAyJ2kCQw/edit

seems to work for me :)

**Comment by JarredC1000** [comment]
Woah, there's no way that was there before.

**Comment by blurymind** [comment]
feel free to close this bug if it's working :)

**Comment by JarredC1000** [comment]
Looks like it was someplace else from where i had looked before. I feel blind.
