### ISSUE TITLE
Issue: Flip tool help text is reversed

### ISSUE THREAD

**Issue by k-wins-it** [piskelapp/piskel#894]
#### Bug description:
The Flip Horizontally tool's help text names the tool "Flip Vertically", and says "`[ALT]` Flip Horizontally". (*see attached screenshot*)
However, the icon suggests that the tool flips the canvas horizontally, and holding alt should flip it vertically.
The behavior of the tool matches the icon, and in fact flips the canvas horizontally, while holding `[Alt]` flips the canvas vertically.

### Steps to reproduce the bug
1. go to piskelapp.com
2. open the editor (sprite does not matter)
3. hover over the flip tool
4. observe that the tool is named "Flip Vertically"
5. click it to find it in fact flips horizontally

### Environment details
* operating system: Windows
* browser (or offline application version): Google Chrome

#### *4. Observe...*
![flip tool tooltip flipped](https://user-images.githubusercontent.com/43500934/62440419-e5859580-b704-11e9-9230-6e6a26b7b67e.png)

**Comment by PatheticMustan** [comment]
I'm pretty sure "Flip Horizontally" means "Flip across the X axis". If so, the text is labelled correctly.

I think the text could be clarified.

Flip horizontally => Flip across X axis
Flip vertically => Flip across Y axis.
