### ISSUE TITLE
Export to PNG spritesheet

### ISSUE THREAD

**Issue by juliandescottes** [piskelapp/piskel#93]
Using the Canvas toDataURL API : 

```
var canvas = document.getElementById("mycanvas");
var img    = canvas.toDataURL("image/png");
```

Concatenate all frames in a single sequence of images and export/save as a single PNG file.

**Comment by AwesomeSauc3** [comment]
I am still not sure how to do it.

**Comment by juliandescottes** [comment]
@AwesomeSauc3 do you mean you don't know how to export as spritesheet ? You can find the "Download PNG" button in the export panel.

![image](https://cloud.githubusercontent.com/assets/1141550/13905987/54384c6e-eece-11e5-87d3-1a1af21952b5.png)
