### ISSUE TITLE
How to download png

### ISSUE THREAD

**Issue by 4tydev** [piskelapp/piskel#970]
Bug description

(this template is intended for bug reports, erase it when requesting features/enhancements)

### Steps to reproduce the bug
1. go to piskelapp.com
2. select a tool
3. ...

### Environment details
* operating system:
* browser (or offline application version):

### Sprite details
* number of frames:
* sprite resolution:
* session duration:

Feel free to include a screenshot of the bug, a .piskel file of the sprite or anything else that can help us investigate.

This may be a dumb question but, how do I download a piskel file as a png from the piskelapp website?

**Comment by TheOnlyTruMe** [comment]
1 Go to export menu (should be the 4th button on the far right panel).
2 Select the PNG tab on the export menu.
3 Click the "Download" button in the Selected Frame Export.
**note this will only download a single frame for multiple frames follow the instructions below.

For multiple frames (zip file):
1 Go to export menu (should be the 4th button on the far right panel).
2 Select the "Zip" tab.
3 Click "Download ZIP" button.
