### ISSUE TITLE
Colorization Tool

### ISSUE THREAD

**Issue by sketchedgrey** [piskelapp/piskel#995]
A colorization tool to change the colour of pixels with all of the same shading is needed in Piskel. This would enhance the general experiance of the app and would function similarly to the swirly paint bucket tool.

**Comment by OPStellar** [comment]
Do you mean 'shading' as in the same light value on an HSL curve?
In that case, why not press for an HSL-specified colorization tool in general?

**Comment by sketchedgrey** [comment]
> Do you mean 'shading' as in the same light value on an HSL curve?
> In that case, why not press for an HSL-specified colorization tool in general?

Well, either way the tool would have the same effect, but that would work to. But yes, what you said about light values and saturation is what I meant.

**Comment by sketchedgrey** [comment]
Sadly never going to gain any traction unless I implement it myself, which at the moment I am not well equipped enough to do so.
